# Generated by Django 5.0.1 on 2024-01-14 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_us_model',
            name='image',
            field=models.ImageField(blank=True, default='http://placehold.it/200x200', null=True, upload_to='about-us/'),
        ),
    ]
