# Generated by Django 5.0.1 on 2024-02-11 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_remove_transaction_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='company_symbol',
            field=models.CharField(max_length=50),
        ),
    ]
