# Generated by Django 5.0.1 on 2024-02-24 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0005_buytransaction_creditbalanceupdate_selltransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buytransaction',
            name='transaction',
        ),
        migrations.RemoveField(
            model_name='selltransaction',
            name='transaction',
        ),
        migrations.AddField(
            model_name='buytransaction',
            name='company_symbol',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='buytransaction',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='buytransaction',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='buytransaction',
            name='transaction_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='buytransaction',
            name='transaction_type',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='buytransaction',
            name='user',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='selltransaction',
            name='company_symbol',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='selltransaction',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='selltransaction',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='selltransaction',
            name='transaction_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='selltransaction',
            name='transaction_type',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='selltransaction',
            name='user',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='company_symbol',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='user',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
