# Generated by Django 5.0.1 on 2024-02-25 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0006_remove_buytransaction_transaction_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buytransaction',
            old_name='price_per_unit',
            new_name='buy_price_per_unit',
        ),
        migrations.RenameField(
            model_name='selltransaction',
            old_name='price_per_unit',
            new_name='sell_price_per_unit',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='price_per_unit',
            new_name='buy_price_per_unit',
        ),
        migrations.AddField(
            model_name='buytransaction',
            name='sell_price_per_unit',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='selltransaction',
            name='buy_price_per_unit',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='sell_price_per_unit',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
