# Generated by Django 5.0.1 on 2024-02-29 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0008_selltransaction_sell_profit_loss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditbalanceupdate',
            name='user',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
