# Generated by Django 5.0.1 on 2024-01-20 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyData', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companydata',
            old_name='last_price',
            new_name='quote_price',
        ),
        migrations.AddField(
            model_name='companydata',
            name='ask',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='companydata',
            name='avg_volume',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companydata',
            name='beta_5y_monthly',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='companydata',
            name='bid',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='companydata',
            name='days_range',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='companydata',
            name='earnings_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='companydata',
            name='eps_ttm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='companydata',
            name='ex_dividend_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companydata',
            name='fifty_two_week_range',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='companydata',
            name='forward_dividend_yield',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='companydata',
            name='market_cap',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='companydata',
            name='one_year_target_est',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='companydata',
            name='open_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='companydata',
            name='pe_ratio_ttm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='companydata',
            name='previous_close',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='companydata',
            name='volume',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
