# Generated by Django 5.0.1 on 2024-01-23 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyData', '0002_rename_last_price_companydata_quote_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydata',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='avg_volume',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='beta_5y_monthly',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='eps_ttm',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='ex_dividend_date',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='one_year_target_est',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='open_price',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='pe_ratio_ttm',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='previous_close',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='quote_price',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='volume',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
