# Generated by Django 5.0.1 on 2024-02-11 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyData', '0003_companydata_description_alter_companydata_avg_volume_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydata',
            name='symbol',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
