# Generated by Django 5.0.1 on 2024-01-14 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_module', '0002_signupmodel_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupmodel',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile_pics/profile.png', max_length=200, null=True, upload_to='profile_pics/'),
        ),
    ]
