# Generated by Django 5.0.1 on 2024-01-28 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_module', '0003_alter_signupmodel_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupmodel',
            name='credit_balance',
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=15),
        ),
    ]
