# Generated by Django 5.0.1 on 2024-01-31 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_module', '0004_signupmodel_credit_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupmodel',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
